version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://genessergio:2QPw0LLB1vWGiRXB@cluster0.nurcc.mongodb.net/eloqualogger?authSource=admin
    depends_on:
      - mongodb